import localeinfo

EMOTION_DICT = {
	1 : {"name": localeinfo.EMOTION_CLAP, "command":"/clap"},
	2 : {"name": localeinfo.EMOTION_CONGRATULATION, "command":"/congratulation"},
	3 : {"name": localeinfo.EMOTION_FORGIVE, "command":"/forgive"},
	4 : {"name": localeinfo.EMOTION_ANGRY, "command":"/angry"},
	5 : {"name": localeinfo.EMOTION_ATTRACTIVE, "command":"/attractive"},
	6 : {"name": localeinfo.EMOTION_SAD, "command":"/sad"},
	7 : {"name": localeinfo.EMOTION_SHY, "command":"/shy"},
	8 : {"name": localeinfo.EMOTION_CHEERUP, "command":"/cheerup"},
	9 : {"name": localeinfo.EMOTION_BANTER, "command":"/banter"},
	10 : {"name": localeinfo.EMOTION_JOY, "command":"/joy"},
	11 : {"name": localeinfo.EMOTION_CHEERS_1, "command":"/cheer1"},
	12 : {"name": localeinfo.EMOTION_CHEERS_2, "command":"/cheer2"},
	13 : {"name": localeinfo.EMOTION_DANCE_1, "command":"/dance1"},
	14 : {"name": localeinfo.EMOTION_DANCE_2, "command":"/dance2"},
	15 : {"name": localeinfo.EMOTION_DANCE_3, "command":"/dance3"},
	16 : {"name": localeinfo.EMOTION_DANCE_4, "command":"/dance4"},
	17 : {"name": localeinfo.EMOTION_DANCE_5, "command":"/dance5"},
	18 : {"name": localeinfo.EMOTION_DANCE_6, "command":"/dance6"},
	19 : {"name": localeinfo.EMOTION_SELFIE, "command":"/selfie"},
	20 : {"name": localeinfo.EMOTION_DANCE_7, "command":"/dance7"},
	21 : {"name": localeinfo.EMOTION_DOZE, "command":"/doze"},
	22 : {"name": localeinfo.EMOTION_EXERCISE, "command":"/exercise"},
	23 : {"name": localeinfo.EMOTION_PUSHUP, "command":"/pushup"},
	24 : {"name": localeinfo.EMOTION_SIRENA, "command":"(emoji1)"},
	25 : {"name": localeinfo.EMOTION_CALL, "command":"(emoji2)"},
	26 : {"name": localeinfo.EMOTION_CHARGING, "command":"(emoji3)"},
	27 : {"name": localeinfo.EMOTION_CELEBRATION, "command":"(emoji4)"},
	28 : {"name": localeinfo.EMOTION_WEATHER, "command":"(emoji5)"},
	29 : {"name": localeinfo.EMOTION_ALCOHOL, "command":"(emoji6)"},
	30 : {"name": localeinfo.EMOTION_HUNGRY, "command":"(emoji7)"},
	51 : {"name": localeinfo.EMOTION_CLAP_KISS, "command":"/kiss"},
	52 : {"name": localeinfo.EMOTION_FRENCH_KISS, "command":"/french_kiss"},
	53 : {"name": localeinfo.EMOTION_SLAP, "command":"/slap"},
}
