say_title ( string . format ( "%s:" , mob_name ( npc . get_race ( ) ) ) ) 
say ( "" ) 
local lang = pc . get_language ( ) 
say ( gameforge [ lang ] . guild_manage . _3 ) 
local s = select ( gameforge [ lang ] . common . yes , gameforge [ lang ] . common . no ) 
if s == 1 then 
say ( gameforge [ lang ] . guild_manage . _4 ) 
pc . destroy_guild ( ) 
pc . setqf ( "new_disband_time" , get_global_time ( ) ) 
pc . setqf ( "new_withdraw_time" , get_global_time ( ) ) 
end 
